# RocketMQ
rocketmq.name-server=127.0.0.1:9876
rocketmq.consumer.group=prometheus_adapter_group
rocketmq.consumer.topic=metrics_topic

# Prometheus
prometheus.remote-write.url=http://localhost:9090/api/v1/write
